spring:
  application:
    name: elams-backend
  profiles:
    active: dev

server:
  port: 8080

security:
  jwt:
    secret: YOUR_SUPER_SECRET_KEY_32_CHAR_MINIMUM_123456
    access-token-expiration: 3600000   # 1 hour
